# Generated by Django 4.2.6 on 2023-10-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_updared_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10),
        ),
    ]
