# Generated by Django 4.2.6 on 2023-10-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gender',
        ),
    ]
