# Generated by Django 4.2.6 on 2023-10-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], default='M', max_length=1),
        ),
    ]
